-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "rmktAllowedDays" TEXT NOT NULL DEFAULT '1,2,3,4,5',
ADD COLUMN     "rmktIntervalMinutes" INTEGER NOT NULL DEFAULT 1440,
ADD COLUMN     "rmktMaxDelaySec" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN     "rmktMaxFollowUps" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "rmktMaxPerDay" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rmktMinDelaySec" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "rmktScripts" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "rmktWindowEnd" TEXT NOT NULL DEFAULT '18:00',
ADD COLUMN     "rmktWindowStart" TEXT NOT NULL DEFAULT '09:00';
